### PR TITLE
Extend the starting question method to allow resumability feature

### PR DESCRIPTION
**Pull request by musayann**
Merged the next question method with the starting question behaviour in iteration, so the first question in each iteration becomes the latest one possible allowing the resumability feature

### CODE REVIEW

**Comment by musayann** [comment]
> Where and why do you need this?
> 
> the starting question is coming from the iteration and the next question after answering a question should be returned as a response from the answer submission.

I was thinking we can redirect the user to the this route to get next question when resuming the iteration or after answering a question.

Or when can merge the behavior of the next question in the starting _question_id method in iteration to allow users to resume their iteration

**Comment by bumi** [comment]
I don't care that much about resuming the iteration right now, because first we have to be able to actually answer questions. - that is more important, until we don't have the basics done resuming is also not possible.

but then I also think we get the question ID in the iteration, so we don't need that extra redirect... but let's get to that when we actually need it.

**Comment by musayann** [comment]
The problem now is, the current homepage we have(when the user slug has been provided), shows the all the iteration that the user has and the option to create a new one. when the user creates a new one the first question just kick in, when the user clicks an existing iteration the app is supposed to show them where their left off. 

The problem now is if we like drop this feature we will continue with the homepage that we currently or ??

**Comment by bumi** [comment]
we have to prioritize here. 
we should do that later. as long as a user can not fully use the questionnaire, there is no need to resume it.  
we need set the focus on getting one thing done, before adding more features that also mean more complexity.

**Pull request closed without merging**
